### ISSUE TITLE
Don't save url-proxy-services into customize

### ISSUE THREAD

**Issue by stardiviner** [rayw000/use-proxy#1]
Hi, @rayw000 thanks for great package. I switched from my developed package `proxy-mode` to your package. 😄  👍🏻 

I suggest don't save `url-proxy-services` info into customize. Because use usually save proxy info in init config. No need to set in customize twice.

If must save, then at lease put it before messages like `(message "Global proxy mode off")`. I always don't know whether disabled proxy or enabled proxy. I have to check out `*Messages*` buffer. That's really anonying.

**Comment by rayw000** [comment]
Hi @stardiviner 

Glad to hear that this package is helpful to you! 😃

Saving `url-proxy-services` is because this package would automatically load proxy settings from shell environments such as `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`, in which case someone may not have `url-proxy-services` set at startup. If we do not save the value of `url-proxy-services`, people may need to reconfigure their proxy everytime they restart Emacs by invoking `use-proxy-toggle-proto-proxy`.

It's a great suggestion that `customize-save-variable` should come before `message` to avoid meaningful message overlapped. I've already updated in https://github.com/rayw000/use-proxy/commit/3f1db9094e12f6847c3d357922002cbf7657364c.

**Comment by stardiviner** [comment]
Thanks for quick update. 👍🏻
